# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-17 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_describes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='describes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_ph',
            field=models.ImageField(upload_to='uploadImages', verbose_name='标签图'),
        ),
    ]
