# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-17 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180717_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_ph',
            field=models.ImageField(default=1, upload_to='uploadImages', verbose_name='类目图'),
            preserve_default=False,
        ),
    ]
