# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-18 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_category_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='loves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
