# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-30 15:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth_ex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OAuth_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=12)),
                ('img', models.ImageField(upload_to='uploadImages')),
            ],
        ),
        migrations.AddField(
            model_name='oauth_ex',
            name='oauth_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.OAuth_type'),
        ),
        migrations.AddField(
            model_name='oauth_ex',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
